config/routes.rb
Chat::Application.routes.draw do
  match "chat" => "chatter#chat"

  match "/upload" => "chatter#upload"

  post "chatter/create"
  match "/upload" , to: "chatter#upload"
  match "/save" , to: "chatter#save"

  get "chatter/delete"
   match '/server' , to: 'chatter#paserver'
   match '/p2' , to: 'chatter#page2'
   root :to => 'chatter#login'

  

end

app/models/upload.rb
class Upload < ActiveRecord::Base
	include Paperclip::Glue
	attr_accessible :file, :name
	has_attached_file :file
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/chatter_controller.rb
class ChatterController < ApplicationController

require 'redis'

before_filter :make_websocket , only: [:paserver]

  def paserver
  end

  def chat
    f = $redis.LLEN 'msg'
    @a = $redis.lrange('msg',0,f)
  end

  def page2
  end

  def save
    @up = Upload.new(params[:upload])
    @up.name = cookies[:name]
    @up.save
    redirect_to upload_path
  end

  def upload
    @up = Upload.new  
    @all = Upload.all
  end
 
  def login
    if cookies[:name]
      redirect_to chat_path
    end
  end

  def create
    cookies[:name] = params[:name]
    redirect_to chat_path 
  end

  def delete
    cookies.delete :name
    redirect_to root_path
  end

#Completely different world below !!!


  def make_websocket
  require 'em-websocket'
  require 'sanitize'

soc = []



EM::WebSocket.start(host: '10.20.4.130' , port: 4000) do |ws|

  ws.onopen{soc << ws;puts "#{soc.length} clients present";}
  ws.onmessage { |msg| ; soc.each do |s| 
        msg = Sanitize.clean(msg.html_safe , :elements => %w(font) , :attributes => {'font' => ['color']})
				s.send("#{msg}")
				end ; $redis.LPUSH 'msg', "#{msg}" }
  ws.onclose {puts "Someone dissconected " ; soc.delete(ws)}
  end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatter_helper.rb
module ChatterHelper
end

app/views/chatter/_helper.js.erb
<script>
$(document).ready(function(){
var n=0;
  function post_server(mes){
  $("#messages").prepend('<p style = "color: red ;background-color: yellow"><font size=4 >'+mes+"<font></p>");
  };
  function post(mes) {
  $("#messages").prepend('<p style = "color: blue ; background-color: yellow"><font size=4 >'+mes.data+"<font></p>").hide().fadeIn('slow');
  };
  // function history(mes) {
  //   var html=mes;
  // $("#messages").append('<p style = "color: green"><font size=4 >'+html+"</font></p>").hide().fadeIn('slow');
  // };
  function post_two(mes) {
  $("#messages").prepend('<p style = "color: green"><font size=4 >'+mes.data+"</font></p>").hide().fadeIn('slow');
  };
  var name = "<font color="+"red"+"><%= cookies[:name].to_s %></font>"
  //Change the below number for the LAN !!!
// var address = "ws:169.254.96.158:4000";
// var address = "ws:10.0.2.15:4000"


var address = "ws:10.20.4.130:4000"
var webSocket;
if (typeof MozWebSocket === "undefined") 
  ws = new WebSocket(address);
else
{
  if ( $.browser.mozilla ) {
  ws = new MozWebSocket(address);
} else {
  ws = new WebSocket(address);
}
}
  // ws = new WebSocket(address);
  ws.onopen = function() { ws.send(name+"  "+"Joined the chat !!!");}
  ws.onclose = function() { post_server("Server connection lost");ws.send(name+" "+"disconnected !!")} 
  ws.onmessage = function(msg)  {post_two(msg);} 
  
$('#chat_message').keypress(function(e) {
  if (e.keyCode === 13){
  var message = document.getElementById("chat_message")
//  alert(message.value);
  ws.send(name+": "+message.value);
  message.value = "";
  }});
});
</script>

app/views/chatter/_helper2.js.erb
    <script src='http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js'></script>
    <script>
$(document).ready(function(){
  function post_server(mes){
  $("#messages").prepend(mes);
  };
  function post(mes) {
  $("#messages").append(mes.data);
  };

  ws = new WebSocket("ws:169.254.96.158:4000");
  ws.onopen = function() { ws.send("Connected to Server");}
  ws.onclose = function() { post_server("Server connection lost");} 
  ws.onmessage = function(msg)  {post("<font color='green'>"+msg+"/font");} 


$('#chat_message').keyup(function(e) {
  //if (e.keyCode === 13){
  var message = document.getElementById("chat_message")
//  alert(message.value);
  ws.send(message.value);
  message.value = "";
//  }
});
});
</script>

app/views/chatter/chat.html.erb
<%= render 'helper.js.erb' %>
<div id="side-bar">
<h2 font >Crypt your message</h2>
<font color="white"><%= text_field("chat", "message" , {remote: true , size: 80}) %></font>
</div>
<div id="link">
<%= button_to "Upload and Download" , upload_path ,{method: 'get'} %>
	</div>
<div id="messages">
	<% @a.each do |f| %>
	<p style = "color: green"><font size=4 ><%= sanitize f.html_safe , :tags => %w(font) , :attributes => %w(color)%></font></p>
	<% end %>
</div>

app/views/chatter/login.html.erb
<%= form_tag("/chatter/create", :method => "post") do %>
  <font color="blue"><%= label_tag(:name, "Team Name") %></font>
  <%= text_field_tag(:name) %>
  <%= submit_tag("Submit") %>
<% end %>

app/views/chatter/page2.html.erb
<body bgcolor="orange">
<%= render 'helper2.js.erb' %>
<%= text_field("chat", "message" , {remote: true , size: 70}) %>
<div id="messages"></div>
</body>

app/views/chatter/save.html.erb
<font color="green">
<%= @up.name %>
<%= params[:upload] %>
</font>

app/views/chatter/upload.html.erb
<font color="green">
<h1> Uploads And Downloads !!</h1></font>
<%= form_for(@up , url: save_path , :html => { :multipart => true }) do |f| %>
<%= f.file_field :file %>
<%= f.submit "Submit" %>
<% end %>
<% @all.each do |f| %>
<h3> <font color="red"><%= f.name %></font> <font color="white">uploaded</font> <%= link_to "File" , f.file.url(:original, false ) %><br /></h3>
<% end %>
</font>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chat</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body background="blac.png">

<%= yield %>

</body>
</html>